### ISSUE TITLE
Filtering by prefix performance issues

### ISSUE THREAD

**Issue by m22spencer** [janxious/BT-FYLS#2]
RT (and possibly other modpacks) are shipping with large(121 currently) log prefix filtering settings.

The prefix filtering code for this is rather suboptimal and causes a decent amount of logging overhead.
https://github.com/BattletechModders/BT-FYLS/blob/master/Core.cs#L60-L64

I'm just adding this for tracking purposes.

**Comment by janxious** [comment]
Yeah I can think of a few things that would do this faster but they are more complicated. 🗡️

**Comment by janxious** [comment]
https://github.com/BattletechModders/BT-FYLS/releases/tag/v1.4.1 has fix, seems faster in some light testing
